# summary: use Ctrl-a as the prefix key, spawn 3 panes with `just rviz` in the hidden one, enable mouse control, disable auto-rename windows

# use Ctrl-a as the prefix key instead
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# don't rename windows automatically
set-option -g allow-rename off

# enable mouse control
set -g mouse on

new -A -s maverick -n rviz just rviz
neww -n launch
splitw -v -p 50 -t 0
