# summary: spawn a window with split panes, one of which automatically runs rviz, enable mouse control

# enable mouse control
set -g mouse on

# rows
new -A -s maverick -n launch just rviz
splitw -v -p 50 -t 0

# split top row
splitw -h -p 50 -t 0

# split bottom row
splitw -h -p 50 -t 2
