<?xml version="1.0"?>
<package format="3">
  <name>zed_publisher</name>
  <version>0.0.1</version>
  <description>Central node for publishing ZED frames</description>

  <maintainer>Aditya Suri</maintainer>
  <license></license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>utils</exec_depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
