#!/usr/bin/env python3
import csv
from pathlib import Path

from common import ROOT, die

DMS_DIR = ROOT / "waypoints" / "dms"
DECIMAL_DIR = ROOT / "waypoints" / "decimal"

MARKER_NAME = "GENERATED_DO_NOT_EDIT"
MARKER_TEXT = (
    "Files in this directory are generated by scripts/convert_waypoint.py.\n"
    "Do not edit them by hand: edit the source CSVs in waypoints/dms/ and re-run the converter.\n"
    "Hand edits will be overwritten on the next run.\n"
)

DmsWaypoint = tuple[str, float, float]  # (name, latitude, longitude) with packed-DMS coordinates
DecimalWaypoint = tuple[str, float, float]  # (name, latitude, longitude) in decimal degrees


def packed_dms_to_decimal(value: float) -> float:
    """Convert a packed DMS float (DD.MMSSsssss) to decimal degrees."""
    sign = -1 if value < 0 else 1
    value = abs(value)

    degree = int(value)
    remainder = round((value - degree) * 100, 10)
    minute = int(remainder)
    second = round((remainder - minute) * 100, 10)

    return sign * (degree + minute / 60 + second / 3600)


def extract(input_path: Path) -> list[DmsWaypoint]:
    waypoints: list[DmsWaypoint] = []
    with input_path.open(newline="") as f:
        reader = csv.reader(f)

        header = next(reader, None)
        if header is None:
            die(f"{input_path} is empty")

        if [c.strip().lower() for c in header] != ["name", "latitude", "longitude"]:
            die(f"{input_path}:1: expected header 'name,latitude,longitude', got {header!r}")

        for i, row in enumerate(reader, start=2):
            if not row:
                continue

            if len(row) != 3:
                die(f"{input_path}:{i}: expected 3 columns (name,latitude,longitude), got {row!r}")

            name, latitude_str, longitude_str = (cell.strip() for cell in row)
            for label, raw in (("latitude", latitude_str), ("longitude", longitude_str)):
                try:
                    float(raw)
                except ValueError:
                    die(f"{input_path}:{i}: non-numeric {label} {raw!r}")

            waypoints.append((name, float(latitude_str), float(longitude_str)))

    return waypoints


def convert(waypoints: list[DmsWaypoint]) -> list[DecimalWaypoint]:
    return [
        (name, packed_dms_to_decimal(latitude), packed_dms_to_decimal(longitude))
        for name, latitude, longitude in waypoints
    ]


def write(waypoints: list[DecimalWaypoint], output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", newline="") as f:
        writer = csv.writer(f, lineterminator="\n")
        writer.writerow(["name", "latitude", "longitude"])
        for name, latitude, longitude in waypoints:
            # 7dp for latitude / longitude. See waypoints/README.md for the rationale; keep these in sync.
            writer.writerow([name, f"{latitude:.7f}", f"{longitude:.7f}"])


def convert_file(input_path: Path) -> None:
    output_path = DECIMAL_DIR / input_path.name

    dms_waypoints = extract(input_path)
    waypoints = convert(dms_waypoints)
    write(waypoints, output_path)
    print(f"Converted {len(waypoints)} waypoint(s): {input_path.relative_to(ROOT)} -> {output_path.relative_to(ROOT)}")


def write_marker() -> None:
    DECIMAL_DIR.mkdir(parents=True, exist_ok=True)
    (DECIMAL_DIR / MARKER_NAME).write_text(MARKER_TEXT)


def main() -> None:
    paths = sorted(DMS_DIR.glob("*.csv"))
    if not paths:
        die(f"no .csv files found in {DMS_DIR.relative_to(ROOT)}/")

    for path in paths:
        convert_file(path)

    write_marker()


if __name__ == "__main__":
    main()
