name: lint

permissions:
  contents: read
  packages: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install any new deps (top-up)
        run: rosdep install --from-paths . --ignore-src -r -y

      - name: Install tooling deps
        run: pip install ".[tooling]"

      - name: Lint
        run: just lint
